version: v1.1.0
steps:
  - cmd: mcr.microsoft.com/acr/acr-cli:0.14 purge --registry $RegistryName --filter "cat-ftx1:^(?!latest$).*" --ago 30d --untagged --keep 5
    disableWorkingDirectoryOverride: true
    timeout: 3600
